apiVersion: v1
kind: Service
metadata:
  name: {{ include "elasticsearch.fullname" . }}
  labels:
    {{- include "elasticsearch.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.elasticsearchPort }}
      targetPort: elasticsearch
      protocol: TCP
      name: elasticsearch
    - port: {{ .Values.service.communicationPort }}
      targetPort: communication
      protocol: TCP
      name: communication
  selector:
    {{- include "elasticsearch.selectorLabels" . | nindent 4 }}
